In [189]:
import pandas as pd

In [190]:
import numpy as np
print("Successfully ")
print("Pandas :",pd.__version__)
print("Numpy :",np.__version__)

Successfully 
Pandas : 2.3.3
Numpy : 2.3.5


Lets start the Python Practice 

For Loop 
Syntax 
for i in range(0,10)

In [191]:
for i in range(1,11):
    print(2*i)

2
4
6
8
10
12
14
16
18
20


In [192]:
no=int(input("Enter Number: "))
for i in range(1,11):
    print(no*i)

ValueError: invalid literal for int() with base 10: ''

While Loop 
Syntax: 
while condition:

In [ ]:
no=int(input("Enter Number: "))
i=1
while i<11:
    print(i*no)
    i+=1

34
68
102
136
170
204
238
272
306
340


Functions in python
def keyword is used to define function in python
def function_name(parameters):
    code
    return value


In [ ]:
def grettings(name):
    print(f"Hello {name}")

grettings("Karan")

Hello Karan


In [ ]:
def square(n):
    return n*n

result= square(5)
print("Square is ",result)

Square is  25


List
list is defined in sqaure brackets, It is mutable (Changeble), Ordered (follows indexing), allows duplicate values

In [ ]:
list1=["Mouse","keyboard","printer"]
list1[1]="Monitor"
list1.append("CPU")
print(list1)

['Mouse', 'Monitor', 'printer', 'CPU']


Tuple
tuple is defined in round brackets, It is Immutable (changes not allowed), Ordered (Follows indexing), allows duplicate values

In [ ]:
num=(1990,1880,1770)
num[1]=1660


TypeError: 'tuple' object does not support item assignment

Dictionary
Dictionary is decalred using {}. It is a key value pair. Keys are unique and values are accessed through keys and assigned through keys. dict.values funtion is used to access list of values. dict.keys function is used to access the list of keys

In [ ]:
# Creating a dictionary to store user profile data
user_profile = {
    "username": "coder_karan",
    "language": "Python",
    "experience_level": "Intermediate",
    "completed_lessons": 4
}

# 1. How to access a value using its key
print("Current Language:", user_profile["language"])

# 2. How to update an existing value
user_profile["completed_lessons"] = 5

# 3. How to add a brand new key-value pair
user_profile["github_connected"] = True

print("\nUpdated Profile:", user_profile)

Current Language: Python

Updated Profile: {'username': 'coder_karan', 'language': 'Python', 'experience_level': 'Intermediate', 'completed_lessons': 5, 'github_connected': True}


Set
Set is defined in {}. No duplicate values allowed, it is unordered , mutable.

In [ ]:
# Creating a set with duplicate items
languages_set = {"Python", "JavaScript", "C++", "Python", "C++"}

# Python automatically removes the duplicates!
print("Unique Languages:", languages_set)

# Adding a new item
languages_set.add("HTML")

# Checking if an item exists in a set (incredibly fast)
print("Is Python in the set?", "Python" in languages_set)

Unique Languages: {'JavaScript', 'C++', 'Python'}
Is Python in the set? True


Escape Characters
\n - This is used for New Line
\t - This is used for putting Tab in string
\\ - This prints a literal \
\" - This is Used to enter Double inverted comma into string
\' - This is used to enter Single inverted comma into string

Concatination- This is used to add two strings together. this is done using + operator. Concatination can only be done between str to str.

serators = this is used to separator variables by given parameter, By default space is added by python. sep keyword is used to add seaparator

end = This is used to enter the value which we want to add at the end of the line. This is done using end keyword

In [ ]:
print("Hello Karan \nI have completed my Engineering.")

Hello Karan 
I have completed my Engineering.


In [ ]:
print("Hello Karan\tHow are you?")

Hello Karan	How are you?


In [ ]:
print("My file address is c:\\user\\desktop\\pythonpractice")

My file address is c:\user\desktop\pythonpractice


In [ ]:
print("I have completed my engineering from \"Sanidp University\" ")

I have completed my engineering from "Sanidp University" 


In [ ]:
print("I am learning \'Python\' ")

I am learning 'Python' 


In [ ]:
a="Hello"
b="Karan"
print(a+b)
print(a+"Mr."+b)
print(a,b,"Good Morning")

HelloKaran
HelloMr.Karan
Hello Karan Good Morning


In [ ]:
print("c","cpp","python","java","OOP")
print("c","cpp","python","java","OOP",sep=":")
print("c","cpp","python","java","OOP",sep="||")

c cpp python java OOP
c:cpp:python:java:OOP
c||cpp||python||java||OOP


F string you put an f before your quotation marks and place the variable name inside curly braces {}.

In [ ]:
name = "Karan"
print(f"Hello, {name}")

Hello, Karan


Class: The blueprint or recipe. It defines what data an object will hold and what it can do, but it doesn't contain real data yet.

Object: The actual item built from the blueprint. It is an instance of the class filled with real, specific data.
class keyword is used to create class, __init__, this keyword is used to create constructor in python, constructor is used to initialize the object's properties (Attributes) the momnet it created/


Self, this keyword simply refers to the specific object you are currently creating or dealing with. When you call laptop1.show_specs(), Python implicitly translates self to mean laptop1, accessing its specific brand and RAM.

In [ ]:
class device:

    #constructor
    def __init__(self,brand,ram,processor):
        self.brand=brand
        self.ram=ram
        self.processor=processor
    
    def show(self):
        print("Brand : ",self.brand)
        print("Ram : ",self.ram)
        print("Processor: ",self.processor)
    
karan=device("Samsung","8GB","Mediatek")
yash=device("Redmi","12GB","Snapdragon")

karan.show()
yash.show()

    

Brand :  Samsung
Ram :  8GB
Processor:  Mediatek
Brand :  Redmi
Ram :  12GB
Processor:  Snapdragon


In [ ]:
class developer:
    def __init__(self,name,lang,git):
        self.name=name
        self.lang=lang
        self.git=git

    def intro(self):
        return f"Hello,I am {self.name}. I code in {self.lang} and my github profile is {self.git}"

karan=developer("Karan","Cpp","Karan-Chavan-04")
yash=developer("Yash","Python","Yash-Chavan-06")
print("Karan's Intro :",karan.intro())
print("Yash's Intro :",yash.intro())


Karan's Intro : Hello,I am Karan. I code in Cpp and my github profile is Karan-Chavan-04
Yash's Intro : Hello,I am Yash. I code in Python and my github profile is Yash-Chavan-06


Encapsulation: Hiding internal data and only allowing access through methods.

Inheritance: Creating a new class based on an existing one so it reuses the code.

Polymorphism: Allowing different classes to have methods with the same name but different behaviors.

Abstraction: Hiding complex implementation details and showing only the essential features.


Inheritance allows you to create a new class (a Child class) that inherits all the attributes and methods of an existing class (a Parent class). This is a lifesaver because it prevents you from copying and pasting the same code across different classes.


In [ ]:
class developer:
    def __init__(self,name,lang):
        self.name=name
        self.lang=lang

    def intro(self):
        print(f"Hello, I am {self.name} and I code in {self.lang}")

class AI_engineer(developer):

    def build(self):
        print(f"{self.name} is training a custom AI agent using {self.lang}")

agent_dev=AI_engineer("Karan","Python")

agent_dev.intro()
agent_dev.build()
    

Hello, I am Karan and I code in Python
Karan is training a custom AI agent using Python


Multilevel Inheritance 

In this multiple classes are inherited in one class, to access the variables and functions of other classes. everything is same as single inheritance, just while entering class name while inheriting the parent class we will enter another parent by separating with comma

class parent1:
    code
class parent2:
    code
class child(parent1,parent2):
    code


In [ ]:
class coder:
    def __init__(self):
        print("Writing clean code.....")
    
    def show(self):
        print("Writing Python code.....")

class ai:
    def __init__(self):
        print("PyTorch")
    def show2(self):
        print("Analyzing data patterns using machine learning.....")

class dev(coder,ai):
    def __init__(self):
        coder.__init__(self)
        ai.__init__(self)

    def display(self):
        print("Inside dev class.....")

obj=dev()
obj.show()
obj.show2()
obj.display()


Writing clean code.....
PyTorch
Writing Python code.....
Analyzing data patterns using machine learning.....
Inside dev class.....


Whenever both have the constuctor chile class will execute first parent's constructor only. if we want to run other parent's contructor we will have to call it explicitly inside child's contructor as shown in above example.......

Multilevel Inheritance

as name suggests, it is a inheitance in which muttiple classes are inherted but in stepwise format, like below....

class grandparent:
    code......
class parent(grandparent):
    code......
class child(parent):
    code......

Hierarchical Inheritance

in this singe class is inherited by multiple classes

class car:
    code.....
class audi(car):
    code......
class mercedes(car):
    code......
class bmw(car):
    code......


Hybrid Inheritance

In this multiple types of inheritance are combined


Polymorphism 

this is the third piller in OOP, in this different classes can have method with exact same name but different behaviour....we use it through method overriding.

In [ ]:
class vehicle:
    def start_engine(self):
        print("Generic Engine Starting.......")

class car(vehicle):
    def start_engine(self):
        print("Car engine purrs: Vroom Vroom!")

class bike(vehicle):
    def start_engine(self):
        print("Bike Engine revs: Braap braap...!")

obj=car()
obj2=bike()
obj.start_engine()
obj2.start_engine()

Car engine purrs: Vroom Vroom!
Bike Engine revs: Braap braap...!


Polymorphism

The last pillar of OOP is Encapsulation. In simple terms, it means bundling the data (attributes) and the methods (functions) together inside a class, and crucially, restricting direct access to some of an object's components.

In Python, we implement this using naming conventions to define access levels:

Public members: Accessible from anywhere outside the class (e.g., self.name).

Protected members: Indicated by a single underscore (e.g., self._salary). It's a convention telling other programmers, "Don't touch this from outside, it's internal."

Private members: Indicated by a double underscore (e.g., self.__password). Python performs "name mangling" to make these strictly hidden from outside the class.



In [ ]:
class bank:
    def __init__(self):
        self.owner="Karan"
        self.__balance=0

    def add(self,amount):
        self.__balance=amount

    def show(self):
        print(self.__balance)
    
cust=bank()
cust.add(5000)
cust.show()
cust.__balance=10000
cust.show()

5000
5000


above example was for encapsulation with protected constraint

How Protected (_) Works
Technically speaking, Python does absolutely nothing to restrict a protected variable. It doesn't mangle the name, and it won't block you if you try to change it from the outside.

Instead, the single underscore is a universal signal to other developers that says: "Hey, this variable is intended for internal use inside this class and its child classes. Please don't modify or access it directly from the outside."

In [ ]:
class Bank:
    def __init__(self):
        self.owner = "Karan"
        self._code = 1234  # Protected variable (Single underscore)
    def show_code(self):
        print("Internal Code:", self._code)
cust = Bank()
cust.show_code()
cust._code = 9999 
cust.show_code()

Internal Code: 1234
Internal Code: 9999


If you run this code, you will see that the value successfully changes to 9999. Python allows it because there is no mechanical enforcement.

Why do we use it if it doesn't lock anything?
Inheritance Access: Unlike private variables (which child classes can't access easily because of name mangling), a child class can access and use a protected variable perfectly. It behaves like a shared asset between a parent and a child class.

Developer Communication: In large production codebases, seeing a _ immediately tells a developer, "Don't touch this directly in your scripts; use a proper method instead." Modern IDEs (like VS Code) will even show a subtle warning hint if you try to call a protected member outside its class structure.

Sting Functions

Case Modifications: lower(),upper(),title(),caputalize()

searching and replacing: replace(old,new),find(subsutring),count(substring)

Splitting and Joining : split(separator) : Splits a string into a list of substrings based on a delimiter (defaults to whitespace)
                        join(iterable) : Joins the elements of an iterable (like a list) into one string, using the host string as the separator

Cleaning and trimming: strip() :Removes whitespace (or specified characters) from both ends.
                        lstrip() : Removes whitespace from the left end.
                        rstrip() : Removes whitespace from the right end.
                        

In [ ]:
text = "hello WORLD"

print(text.lower())       # "hello world"
print(text.upper())       # "HELLO WORLD"
print(text.title())       # "Hello World"
print(text.capitalize())  # "Hello world"

hello world
HELLO WORLD
Hello World
Hello world


In [ ]:
phrase = "banana"

print(phrase.replace("an", "or"))  # "borana"
print(phrase.find("na"))           # 2
print(phrase.count("a"))           # 3

borora
2
3


In [ ]:
# Splitting
csv_data = "apple,banana,cherry"
fruits = csv_data.split(",")  
print(fruits)  # ['apple', 'banana', 'cherry']

# Joining
words = ["Python", "is", "awesome"]
sentence = " ".join(words)    
print(sentence)  # "Python is awesome"

['apple', 'banana', 'cherry']
Python is awesome


In [ ]:
user_input = "   Python is best language for GenAI   "
print(user_input.strip())  # "Python is best language for GenAI"

Python is best language for GenAI


In [ ]:
str="  python dashboard  "
str2=str.strip()
print(str2.upper())

PYTHON DASHBOARD


In [ ]:
file_name="index.html"
print(file_name.endswith(".html"))

True


In [ ]:
str="Tailwind CSS Animations"
print(str.replace(" ","-"))

Tailwind-CSS-Animations


In [ ]:
#Clean Input Pipeline

first_name=input("Please Enter Your First Name: ")
last_name=input("Please Enter Your Last Name: ")
email=input("Enter Your Email Address: ")
print(f"{first_name.title()} {last_name.title()} <{email.lower()}>")

Karan Chavan <karanchavan@gmail.com>


Exception Handling 

In programming, things go wrong. A user might try to divide by zero, pass a string instead of a number, or look for a file that doesn't exist. If you don't handle these errors, your program instantly crashes.

Exception handling lets you catch these errors gracefully so your application stays alive.

We use a try-except block. Python will attempt to run the code inside the try block. If an error occurs, it instantly jumps to the except block instead of crashing.

In [ ]:
try:
    num=int(input("Enter a number to divide 100 by :"))
    result=100/num
    print(f"Result is {result}")
except ZeroDivisionError:
    print("Error.....You cannot divide a number by Zero")
except ValueError:
    print("Error....Please enter a valid whole number,not text!!")
except Exception as e:
    print(f"An Unexpected error occured : {e}")
finally:
    print("Execution Complete. Cleaning up resources.")

Error....Please enter a valid whole number,not text!!
Execution Complete. Cleaning up resources.


In [ ]:
def get_age():
    try:
        age=int(input("Enter Age :  "))
        if age/1==age:
            print(f"Age is {age}")
    except ValueError:
        print("Age should be in number not in text format")
    except Exception as e:
        print(f"Unexpected error occured : {e}")
    finally:
        print("Code Execution Complete.....")
get_age()

Age should be in number not in text format
Code Execution Complete.....


File Handling

Programs need a way to remember data after they close. File handling lets you read data from external files or write logs/reports to save them permanently.
In modern Python, we always use the with keyword. It opens the file and guarantees it closes automatically when you're done—even if your code crashes in the middle.

Read/Write Modes:
'w': Write mode. Overwrites the file completely if it exists or creates a new one.
'a': Append mode. Adds new text to the end of the data already inside.
'r': Read mode. Opens the file to read its text.


In [ ]:
with open("Karan.txt","w") as file:
    file.write("This is the first file handling program ")
    file.write("\nHope this is writting well....")

print("File Written successfully...")

with open("Karan.txt","r") as file:
    content=file.read()
    print("\n-----File Content-------")
    print(content)


File Written successfully...

-----File Content-------
This is the first file handling program 
Hope this is writting well....


In [ ]:
log=input("Enter Log: ")
with open("Karan.txt","a") as file:
    file.write("\n")
    file.write(log)
log=input("Enter Log: ")
with open("Karan.txt","a") as file:
    file.write("\n")
    file.write(log)
log=input("Enter Log: ")
with open("Karan.txt","a") as file:
    file.write("\n")
    file.write(log)
with open("Karan.txt","r") as file:
    content=file.read()
    print("\n------------FILE DATA---------")
    print(content)



------------FILE DATA---------
This is the first file handling program 
Hope this is writting well....HelloMasterKaranHelloMAster KAran
This 
is 
Finnaly done


In Python, loops can often be simplified. List Comprehensions provide a shorter, highly optimized syntax when you want to create a new list based on the values of an existing list.

Instead of writing a 3- or 4-line for loop, you can condense it all into a single line inside square brackets.

In [ ]:
# The Traditional Way
numbers = [1, 2, 3, 4, 5]
squares = []
for x in numbers:
    squares.append(x * x)

# The List Comprehension Way (Much faster and cleaner!)
squares = [x * x for x in numbers]
print(squares)

[1, 4, 9, 16, 25]


In [ ]:
numbers = [1, 2, 3, 4, 5, 6]
even_squares = [x * x for x in numbers if x % 2 == 0]
print(even_squares)  # [4, 16, 36]

[4, 16, 36]


1. Adding an else block (and if-else ladders)
When you only use an if statement, it acts as a filter and goes at the very end of the comprehension.

But the moment you want an else block, it changes from a filter into an expression. Because of this, the entire if-else structure must move to the front of the comprehension, right after the bracket.

In [ ]:
numbers = [1, 2, 3, 4, 5]
labels = ["Even" if x % 2 == 0 else "Odd" for x in numbers]
print(labels)

['Odd', 'Even', 'Odd', 'Even', 'Odd']


An if-else Ladder (Nested conditions)
You can even string multiple else if conditions together by nesting them sequentially. Let's classify prices as "High", "Medium", or "Low":

In [ ]:
prices = [10, 45, 120]
# Syntax: [Result1 if Cond1 else Result2 if Cond2 else Result3 for x in list]
status = ["High" if x > 100 else "Medium" if x > 30 else "Low" for x in prices]
print(status)  # ['Low', 'Medium', 'High']

['Low', 'Medium', 'High']


2. Nested if Statements
If you want to apply multiple conditions that all must be true (like a nested if), you can just chain them together at the very end of the comprehension. It works exactly like using an and operator.

In [ ]:
numbers = [5, 12, 18, 20, 25, 30]
# Filter: Must be divisible by 2 AND divisible by 3
filtered = [x for x in numbers if x % 2 == 0 if x % 3 == 0]
print(filtered)

[12, 18, 30]


In [ ]:
scores=[45,85,55,92,60]
results=["Pass" if x>=60 else "Fail" for x in scores]
print(results)

['Fail', 'Pass', 'Fail', 'Pass', 'Pass']


Functional Tools: Lambda, Map, & Filter

Sometimes, writing a full multi-line function using def is absolute overkill for a simple task. Python gives us a collection of tools to perform quick data operations on the fly.

A. Lambda Functions (Anonymous Functions)
A lambda function is a tiny, one-line function that doesn't have a name.

Syntax: lambda arguments: expression

In [ ]:
# The traditional way
def add_ten(x):
    return x + 10

# The Lambda way
quick_add = lambda x: x + 10
print(quick_add(5))

15


B. Map Function
map() takes a function and applies it to every single item inside an iterable (like a list) all at once.

In [ ]:
numbers = [1, 2, 3, 4]
# Double every number in the list using map and lambda
doubled = list(map(lambda x: x * 2, numbers))
print(doubled)

[2, 4, 6, 8]


C. Filter Function
filter() takes a function that returns True or False, and uses it to extract only the elements that meet your condition.

In [ ]:
numbers = [10, 15, 20, 25, 30]
# Keep only the numbers greater than 18
large_numbers = list(filter(lambda x: x > 18, numbers))
print(large_numbers)

[20, 25, 30]


In [ ]:
data = [5, 12, 7, 18, 24, 3]
even=list(filter(lambda x: x%2==0,data))
print(even)

[12, 18, 24]


Numpy

If Python lists are like a disorganized pile of storage boxes, NumPy (Numerical Python) is a high-speed, perfectly labeled warehouse. It is the foundation for almost every data science, machine learning, and visualization library in Python (including Pandas, Scikit-Learn, and Matplotlib).

Standard Python lists are flexible because they can hold any object type. But that flexibility makes them slow and memory-heavy.

NumPy arrays (ndarrays) require all elements to be of the same data type (homogeneous). This allows NumPy to store data in contiguous memory blocks and perform mathematical operations on entire arrays instantly—without slow for loops. This process is called vectorization.

1D Array (Vector): A single row of numbers (Shape: (n,)).

2D Array (Matrix): Rows and columns, like a spreadsheet (Shape: (rows, cols)).

3D Array (Tensor): A stack of matrices, often used for images or time-series data (Shape: (depth, rows, cols)).

NumPy is a library we need to import it using import keyword
for array creation array function is used 

lets take one example:

In [ ]:
import numpy as np

# 1. Create a 1D array of hourly wages
wages = np.array([15, 20, 25, 30])

# 2. Give everyone a $5 bonus (Vectorized Addition)
new_wages = wages + 5
print("New Wages:", new_wages) 
# Output: [20 25 30 35]

# 3. Double the wages (Vectorized Multiplication)
doubled = wages * 2
print("Doubled:", doubled) 
# Output: [30 40 50 60]

# 4. Filter arrays easily (Boolean Masking)
high_earners = wages[wages > 22]
print("Wages > 22:", high_earners) 
# Output: [25 30]

Notice how we didn't write for wage in wages? That’s the magic of NumPy's underlying C-optimized architecture running under the hood.

2D Array example

In [ ]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("--- 2D Array ---")
print(matrix)
print(f"Dimensions (ndim): {matrix.ndim}")  # Returns 2
print(f"Shape: {matrix.shape}")              # Returns (2, 3) -> 2 rows, 3 columns
print(f"Data Type: {matrix.dtype}")

--- 2D Array ---
[[1 2 3]
 [4 5 6]]
Dimensions (ndim): 2
Shape: (2, 3)
Data Type: int64


In [ ]:
import numpy as np
Metrics=np.array([[1,2,3],
    [4,5,6],
    [7,8,9]])
print(Metrics)
print(f"Share : {Metrics.shape}")
print(f"Dimensions : {Metrics.ndim}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Share : (3, 3)
Dimensions : 2


3D metrics example

In [ ]:
import numpy as np
tensor=np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ],
    [
        [19,20,21],
        [22,23,24],
        [25,26,27]
    ]
])
print(tensor)
print(f"Share : {tensor.shape}")
print(f"Dimensions : {tensor.ndim}")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Share : (3, 3, 3)
Dimensions : 3


As we have done with arrays and its examples, lets learn multiple built-in functions used arrays

We can break them down into three major categories: Creation Utilities, Statistical Operations, and Reshaping.

1. Fast Array Creation Utilities
Instead of typing out every number manually, NumPy has built-in functions to generate structured arrays instantly.

np.zeros() and np.ones()
Generates an array filled entirely with zeros or ones. This is incredibly useful for initializing weights in machine learning or creating default masks.

In [ ]:
import numpy as np
zeros_array = np.zeros((2, 4)) 
print(zeros_array)
ones_array=np.ones((3,4))
print(ones_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


np.arange()
Like Python's standard range(), but it returns a highly optimized NumPy array. You provide the (start, stop, step).

In [ ]:
even_numbers = np.arange(0, 10, 2)
print(even_numbers)

np.random.rand() and np.random.randint()

In [ ]:
import numpy as np
random_floats = np.random.rand(2, 2)
random_ints = np.random.randint(10, 50, size=20)
print(random_floats)
print(random_ints)

[[0.69498283 0.63785965]
 [0.91554836 0.54834188]]
[19 13 31 24 29 34 36 38 20 23 35 13 13 40 10 16 43 42 31 13]


2. Statistical Aggregations

When you have thousands of data points, you need to extract metrics instantly without loops.

np.min(), np.max(), and np.mean()
Finds the lowest value, highest value, or average across the entire array.

The axis Parameter (Crucial Concept)
What if you don't want the maximum of the whole matrix, but the maximum of each column or row? You use axis.

axis=0 calculates down the columns.

axis=1 calculates across the rows.

In [ ]:
import numpy as np 
matrix = np.array([
    [1, 5, 3],
    [4, 2, 6]
])
print("Max: ",np.max(matrix))  # Output: 6
print("Mean : ",np.mean(matrix)) # Output: 3.5
print("Min: ",np.min(matrix)) #output: 1
# Find the maximum value in each column
print(np.max(matrix, axis=0)) # Output: [4 5 6]
# Find the maximum value in each row
print(np.max(matrix, axis=1)) # Output: [5 6]

Max:  6
Mean :  3.5
Min:  1
[4 5 6]
[5 6]


3. Shape Manipulation

In GenAI and neural networks, you often receive data in one shape (e.g., a flat list of 12 elements) but your model expects another shape (e.g., a 3X4 grid).

np.reshape()
Changes the structure of an array without changing its actual data.

In [ ]:
import numpy as np
flat_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape into 3 rows and 4 columns
grid_3x4 = flat_array.reshape(3, 4)
print(grid_3x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [193]:
import numpy as np
flat_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape into 3 rows and 4 columns
grid_3x3 = flat_array.reshape(3, 3)
print(grid_3x4)

ValueError: cannot reshape array of size 12 into shape (3,3)