Broadcasting : Repeating values across the array/axis
Broadcasting reshapes the arrays to perform operations

In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,4,4])
print(a+b)
c=np.array([4])
print(a+c)

[5 6 7]
[5 6 7]


In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[4],[5]])
print(a+b)

[[5 6 7]
 [6 7 8]]


In [ ]:
import numpy as np
a=np.random.random((2,3,1,5,1,2,1,6,4))
b=np.random.random((1,1,4,5,6,1,5,6,1))
print((a+b).shape)

(2, 3, 4, 5, 6, 2, 5, 6, 4)


In [10]:
import numpy as np
a=np.random.random((2,3,1,5,1,2,1,6,4))
b=np.random.random((2,3,3,5,4,6,4,2,1))
print((a+b).shape)

ValueError: operands could not be broadcast together with shapes (2,3,1,5,1,2,1,6,4) (2,3,3,5,4,6,4,2,1) 

What we learn above is that Broadcasting can reshape to perform the operations but only when the dimensions are same or one so that it can directly multiply and match the dimensions and perform the operations, otherwise it will thorugh error

Advanced Indexing :
Dimensional Indexing
in this indexing is done through array instead of normal values

In [20]:
import numpy as np
a=np.array([[1,2,3]
            ,[4,5,6]
            ,[7,8,9]])
print(a[:,:])
print("values of 1st index Coulmn: ",a[:,1])
print("values of 1st index Row: ",a[1,:])
print("Adding additional Axis to the selection")
print("values of 1st index Row with additional axes: ",a[1,:,np.newaxis])
print("values of 1st index Column with additional axes: ",a[np.newaxis,:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
values of 1st index Coulmn:  [2 5 8]
values of 1st index Row:  [4 5 6]
Adding additional Axis to the selection
values of 1st index Row with additional axes:  [[4]
 [5]
 [6]]
values of 1st index Column with additional axes:  [[2 5 8]]


What we did above was dimensional indexing, newaxis is a function for creating a new axis of a selection which we did thorugh indexing

In [24]:
import numpy as np
a=np.array([[1,2,3]
            ,[4,5,6]
            ,[7,8,9]])
print(a[(0,1)])
print(a[[0,1]])
print(a[[0,2]])

2
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]]


Above, when we use tuple it considers input as 0th row and value of 1st index which is 2. but when we use list it considers input as 0th and 1st Column, just for example we did it with 0th and 2nd column too.

In [26]:
import numpy as np
a=np.array([[1,2,3]
            ,[4,5,6]
            ,[7,8,9]])
print(a[:,[0,2]])
print(a[[0,2],[0,2]])

[[1 3]
 [4 6]
 [7 9]]
[1 9]


Sorting and Searching
sorting in numpy is done though sort() inbuilt function, but there is a slight difference
when we do 
np.sort(a)    this does sorting but temporary and doesn't change the array directly 
whereas, a.sort() sorts the actual array
what happens in a.sort()                  a=np.sort(a)

In [ ]:
import numpy as np
a=np.array([[5,9,8]
            ,[4,1,6]
            ,[7,3,2]])
print("Actual Metrix:\n",a)
print("Sorted by default : \n",np.sort(a))  #by default this sorts on axis=1, Horizontally
print("Sorted on Axis=1:\n",np.sort(a,axis=1))
print("Sorted on Axis=0:\n",np.sort(a,axis=0))  #This will sort on axis=0, vertically

Actual Metrix:
 [[5 9 8]
 [4 1 6]
 [7 3 2]]
Sorted by default : 
 [[5 8 9]
 [1 4 6]
 [2 3 7]]
Sorted on Axis=1:
 [[5 8 9]
 [1 4 6]
 [2 3 7]]
Sorted on Axis=0:
 [[4 1 2]
 [5 3 6]
 [7 9 8]]


Above was the basic knowledge about sorting, we will try to sort completely through this....

In [37]:
import numpy as np
a=np.array([[5,9,8]
            ,[4,1,6]
            ,[7,3,2]])
print("Actual Metrix:\n",a)
print(np.sort(np.sort(a,axis=0),axis=1))

Actual Metrix:
 [[5 9 8]
 [4 1 6]
 [7 3 2]]
[[1 2 4]
 [3 5 6]
 [7 8 9]]


Above we though if we sort it horizontally and vertically together it will give us sorted metrix but it won't for doing that we will have to do different approach, 
for that we will have to use in built function flatten() which will flatten the metrix in a list 

In [40]:
import numpy as np
a=np.array([[5,9,8]
            ,[4,1,6]
            ,[7,3,2]])
print("Actual Metrix:\n",a)
print(np.sort(a.flatten()).reshape(a.shape))

Actual Metrix:
 [[5 9 8]
 [4 1 6]
 [7 3 2]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Look by implementing various functions together we sorted metrix completely and again reshaped it in its original form

Lets move to searching, 
In numpy, argmax(arrayname) this returns the index of highest value, argmin(arrayname) this returns the index of lowest value,nonzero(arrayname) this returns nonzero values from the list
where(condition, arrayname, else)

In [48]:
a=np.array([0.05,0.01,0.87,0.02,0.01,0.03,-4,0.01])
print(np.argmax(a))
print(np.argmin(a))
print(np.nonzero(a))
print(np.where(a>0,a,7))

2
6
(array([0, 1, 2, 3, 4, 5, 6, 7]),)
[0.05 0.01 0.87 0.02 0.01 0.03 7.   0.01]
