Broadcasting : Repeating values across the array/axis
Broadcasting reshapes the arrays to perform operations

In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,4,4])
print(a+b)
c=np.array([4])
print(a+c)

[5 6 7]
[5 6 7]


In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[4],[5]])
print(a+b)

[[5 6 7]
 [6 7 8]]


In [ ]:
import numpy as np
a=np.random.random((2,3,1,5,1,2,1,6,4))
b=np.random.random((1,1,4,5,6,1,5,6,1))
print((a+b).shape)

(2, 3, 4, 5, 6, 2, 5, 6, 4)


In [10]:
import numpy as np
a=np.random.random((2,3,1,5,1,2,1,6,4))
b=np.random.random((2,3,3,5,4,6,4,2,1))
print((a+b).shape)

ValueError: operands could not be broadcast together with shapes (2,3,1,5,1,2,1,6,4) (2,3,3,5,4,6,4,2,1) 

What we learn above is that Broadcasting can reshape to perform the operations but only when the dimensions are same or one so that it can directly multiply and match the dimensions and perform the operations, otherwise it will thorugh error

Advanced Indexing :
Dimensional Indexing
in this indexing is done through array instead of normal values

In [20]:
import numpy as np
a=np.array([[1,2,3]
            ,[4,5,6]
            ,[7,8,9]])
print(a[:,:])
print("values of 1st index Coulmn: ",a[:,1])
print("values of 1st index Row: ",a[1,:])
print("Adding additional Axis to the selection")
print("values of 1st index Row with additional axes: ",a[1,:,np.newaxis])
print("values of 1st index Column with additional axes: ",a[np.newaxis,:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
values of 1st index Coulmn:  [2 5 8]
values of 1st index Row:  [4 5 6]
Adding additional Axis to the selection
values of 1st index Row with additional axes:  [[4]
 [5]
 [6]]
values of 1st index Column with additional axes:  [[2 5 8]]


What we did above was dimensional indexing, newaxis is a function for creating a new axis of a selection which we did thorugh indexing

In [24]:
import numpy as np
a=np.array([[1,2,3]
            ,[4,5,6]
            ,[7,8,9]])
print(a[(0,1)])
print(a[[0,1]])
print(a[[0,2]])

2
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]]


Above, when we use tuple it considers input as 0th row and value of 1st index which is 2. but when we use list it considers input as 0th and 1st Column, just for example we did it with 0th and 2nd column too.

In [26]:
import numpy as np
a=np.array([[1,2,3]
            ,[4,5,6]
            ,[7,8,9]])
print(a[:,[0,2]])
print(a[[0,2],[0,2]])

[[1 3]
 [4 6]
 [7 9]]
[1 9]


Sorting and Searching
sorting in numpy is done though sort() inbuilt function, but there is a slight difference
when we do 
np.sort(a)    this does sorting but temporary and doesn't change the array directly 
whereas, a.sort() sorts the actual array
what happens in a.sort()                  a=np.sort(a)

In [ ]:
import numpy as np
a=np.array([[5,9,8]
            ,[4,1,6]
            ,[7,3,2]])
print("Actual Metrix:\n",a)
print("Sorted by default : \n",np.sort(a))  #by default this sorts on axis=1, Horizontally
print("Sorted on Axis=1:\n",np.sort(a,axis=1))
print("Sorted on Axis=0:\n",np.sort(a,axis=0))  #This will sort on axis=0, vertically

Actual Metrix:
 [[5 9 8]
 [4 1 6]
 [7 3 2]]
Sorted by default : 
 [[5 8 9]
 [1 4 6]
 [2 3 7]]
Sorted on Axis=1:
 [[5 8 9]
 [1 4 6]
 [2 3 7]]
Sorted on Axis=0:
 [[4 1 2]
 [5 3 6]
 [7 9 8]]


Above was the basic knowledge about sorting, we will try to sort completely through this....

In [37]:
import numpy as np
a=np.array([[5,9,8]
            ,[4,1,6]
            ,[7,3,2]])
print("Actual Metrix:\n",a)
print(np.sort(np.sort(a,axis=0),axis=1))

Actual Metrix:
 [[5 9 8]
 [4 1 6]
 [7 3 2]]
[[1 2 4]
 [3 5 6]
 [7 8 9]]


Above we though if we sort it horizontally and vertically together it will give us sorted metrix but it won't for doing that we will have to do different approach, 
for that we will have to use in built function flatten() which will flatten the metrix in a list 

In [40]:
import numpy as np
a=np.array([[5,9,8]
            ,[4,1,6]
            ,[7,3,2]])
print("Actual Metrix:\n",a)
print(np.sort(a.flatten()).reshape(a.shape))

Actual Metrix:
 [[5 9 8]
 [4 1 6]
 [7 3 2]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Look by implementing various functions together we sorted metrix completely and again reshaped it in its original form

Lets move to searching, 
In numpy, argmax(arrayname) this returns the index of highest value, argmin(arrayname) this returns the index of lowest value,nonzero(arrayname) this returns nonzero values from the list
where(condition, arrayname, else)

In [48]:
a=np.array([0.05,0.01,0.87,0.02,0.01,0.03,-4,0.01])
print(np.argmax(a))
print(np.argmin(a))
print(np.nonzero(a))
print(np.where(a>0,a,7))

2
6
(array([0, 1, 2, 3, 4, 5, 6, 7]),)
[0.05 0.01 0.87 0.02 0.01 0.03 7.   0.01]


Iterating: 
Iterating matrix values thorugh for loop is pretty complex what if we have mutliple dimensions in the metrix then we will have to use more for loops which will be complex and this is the traditional methos instead we can use numpy's built in function nditer() what ever the shape is this will iterate properly.

In [15]:
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)
for row in a:
    for ele in row:
        print(ele,end=' ')

print()
for i in np.nditer(a):
    print(i,end=' ')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 1 2 3 4 5 6 7 8 9 10 11 
0 1 2 3 4 5 6 7 8 9 10 11 

look this works same normally with built-in function or normally, but the traditional one will not adopt if the shape changes whereas built-in function will be the same despite changing the shape

In [16]:
import numpy as np
a = np.arange(36).reshape(3,4,3)
print(a)
for row in a:
    for ele in row:
        print(ele,end=' ')

print()
for i in np.nditer(a):
    print(i,end=' ')

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
[0 1 2] [3 4 5] [6 7 8] [ 9 10 11] [12 13 14] [15 16 17] [18 19 20] [21 22 23] [24 25 26] [27 28 29] [30 31 32] [33 34 35] 
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 

In [ ]:
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)
for row in a:
    for ele in row:
        print(ele,end=' ')

print()
for i in np.nditer(a,order='C'):             #Iterating in Row Measure way
    print(i,end=' ')
print()
for i in np.nditer(a,order='F'):             #Iterating in Column Measure way
    print(i,end=' ')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 1 2 3 4 5 6 7 8 9 10 11 
0 1 2 3 4 5 6 7 8 9 10 11 
0 4 8 1 5 9 2 6 10 3 7 11 

op_flags='' is a parameter for nditer which is use to change the default accessing. By default nditer accesses arrays in read-only format where they can not do changes in actual array, but when we give 'readwrite' value to this parameter this can do changes in actual array

with......as it:
it uses iterator as a content manager

In [ ]:
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)

with np.nditer(a, op_flags=['readwrite']) as it:
    for element in it:
        element[...] = element ** 2
        
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


element[...] (Ellipsis Syntax): The [...] syntax tells NumPy: "Assign this new value back into the original memory location that element references."

Note: If you just wrote element = element ** 2, it would rebind the local Python variable name element to a new number, leaving the original array a completely unchanged. Using [...] forces the assignment into the array buffer.

Masking: 
Masking is used to exculde certain values from calculations without removing or replacing them

In [33]:
import numpy as np
arr=np.array([1,2,3,np.nan,4,5,np.inf])
print(arr)
print(arr.mean())
Masked_arr=np.ma.masked_array(arr,mask=[0,0,0,1,0,0,1])
print(Masked_arr)
print(Masked_arr.mean())


[ 1.  2.  3. nan  4.  5. inf]
nan
[1.0 2.0 3.0 -- 4.0 5.0 --]
3.0


Look in above example, when we were trying to get the mean of arr but we were getting nan value cause array was containing nan value, so to masked that both non-integer values we used masked array built in function, in this as shown we have to give the values as parameter that which value we want to mask we have to give 1 and which we don't want to mask we give 0. Once items masked they will not be printed even if we print them as shown above.

above mask parameter is good but it is not feasible as we can do this for small data but what about big arrays we won't be able to do it all by own, in such cases we will use different functions according to the need

ma.masked_greater(array_name, value: )   : In this it will mask the elements which will be greater than given value

ma.masked_inside(array_name, v1: v2: )   : In this it will mask the elements which will be in the range of given vlaues including given values

ma.masked_outside(array_name, v1: v2: )  : In this all items will be masked other than given range

ma.masked_where(condition,array_name)    : In this values which will satify the condition will be masked and other will not

ma.masked_invalid(arr)                   : In this a non-integer value will be masked 

ma.masked_sum(array_name)                : This will return sum of masked array

In [44]:
arr=np.array([[1,2,3],[4,5,6]])
print("Masking Greater than 4: \n",np.ma.masked_greater(arr, value=4 ))
print("Masking Numbers between range 2-4: \n",np.ma.masked_inside(arr, v1=2, v2=4 ))
print("Masking Numbers outside the range 2-4: \n",np.ma.masked_outside(arr,v1=2,v2=4))
print("Masking even numbers : \n",np.ma.masked_where(arr%2==0,arr))

Masking Greater than 4: 
 [[1 2 3]
 [4 -- --]]
Masking Numbers between range 2-4: 
 [[1 -- --]
 [-- 5 6]]
Masking Numbers outside the range 2-4: 
 [[-- 2 3]
 [4 -- --]]
Masking even numbers : 
 [[1 -- 3]
 [-- 5 --]]


Views and Copies

In [45]:
import numpy as np
arr=np.array([1,2,3,4,5])
new_arr=arr[0:3]
print(new_arr)
new_arr[1]=100
print(new_arr)
print(arr)

[1 2 3]
[  1 100   3]
[  1 100   3   4   5]


Above is the Example of View

In above example, We are slicing array and storing it in a new variable, but we are slicing the actual array
new_arr is showing us the same actual array but with different POV. so when we are performing operation on new_arr the changes are actually happening on main array too.


In [48]:
import numpy as np
arr=np.array([1,2,3,4,5])
copy_arr=arr.copy()
new_arr=copy_arr[0:3]
print("Slice of Copy array: ",new_arr)
new_arr[1]=100
print("Slice of Copy array: ",new_arr)
print("Main Array: ",arr)
print("Copy Array: ",copy_arr)

Slice of Copy array:  [1 2 3]
Slice of Copy array:  [  1 100   3]
Main Array:  [1 2 3 4 5]
Copy Array:  [  1 100   3   4   5]


Above is the Example of Copy

Above instead of accessing the direct main array we are first creating the copy in the memory, so when we are accessing the values of copy and doing changes the changes are happeening on copy not on main array, by this way our main array is staying safe 

Basically when we do normal slicing we get the view, but when we do advanced indexing we get a copy let me show you with the example

In [49]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
new_arr=arr[[0,1]]
new_arr[0][0]=100
print(new_arr)
print(arr)

[[100   2   3]
 [  4   5   6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Look when we are doing advance indexing it is giving us the copy instead of view that's why when we are doing changes on new array the changes are not reflecting on main array they are only visible on copy arr

TO understand wheather the array on which we are working is a copy or view we can check it though base function

In [50]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.base)
print(arr.copy().base)
print(arr[0:2].base)

None
None
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Look above when the array is the main array or the copy it doesn't give base but it surely gives base when we are working on view, base actually returns the main array of which view we are checking