In the AI pipeline, Pandas is your data cleaning powerhouse. Before any data gets converted into tensors for neural networks, it spends most of its time sitting in a Pandas DataFrame being filtered, cleaned, and transformed.

1. Core Architecture: Series & DataFrames

Series (1D): A single labeled column (built on top of a 1D NumPy array).

DataFrame (2D): A table with labeled axes (rows and columns), where each column is a Series.

In [1]:
import pandas as pd 
#creating dataframes from a dictionary
data={
    "age":[22,25,28,None],
    "Score":[88,92,None,75],
    "Passed":[True,True,False,False]
}
df=pd.DataFrame(data)
print(df)

    age  Score  Passed
0  22.0   88.0    True
1  25.0   92.0    True
2  28.0    NaN   False
3   NaN   75.0   False


2. Essential ML Data Preprocessing Patterns

When preparing data for AI models, these are the top 4 operations you'll run constantly:

A. Handling Missing Data (Imputation)

Real-world datasets are messy. Neural networks will throw errors if they see NaN (Not a Number) values.

In [5]:
#Check Missing Values
print(df.isnull().sum())

#Fill missing numerical values with the mean/median
df["age"]=df["age"].fillna(df["age"].median())
df["Score"]=df["Score"].fillna(df["Score"].median())

print(df)

age       0
Score     1
Passed    0
dtype: int64
    age  Score  Passed
0  22.0   88.0    True
1  25.0   92.0    True
2  28.0   88.0   False
3  25.0   75.0   False


B. Filtering & Querying (Boolean Masking)

Just like NumPy boolean indexing, Pandas lets you filter rows using logical conditions.

In [7]:
# Filter rows where Score > 80
high_scorers = df[df["Score"] > 80]
print(high_scorers)

    age  Score  Passed
0  22.0   88.0    True
1  25.0   92.0    True
2  28.0   88.0   False


C. Feature Engineering & Mapping

Transforming text categories into numerical data so models can process them.

In [8]:
# Map boolean or categorical strings to 0/1
df["Passed"] = df["Passed"].astype(int)

D. Converting DataFrames back to NumPy Arrays

Once your data is cleaned, you convert it back to NumPy arrays (or PyTorch/TensorFlow tensors) for training.

In [12]:
# Extract features as a raw 2D NumPy array
X = df[["age", "Score" , "Passed"]].values
print(X)  # <class 'numpy.ndarray'>

[[22. 88.  1.]
 [25. 92.  1.]
 [28. 88.  0.]
 [25. 75.  0.]]
