In the AI pipeline, Pandas is your data cleaning powerhouse. Before any data gets converted into tensors for neural networks, it spends most of its time sitting in a Pandas DataFrame being filtered, cleaned, and transformed.

1. Core Architecture: Series & DataFrames

Series (1D): A single labeled column (built on top of a 1D NumPy array).

DataFrame (2D): A table with labeled axes (rows and columns), where each column is a Series.

In [1]:
import pandas as pd 
#creating dataframes from a dictionary
data={
    "age":[22,25,28,None],
    "Score":[88,92,None,75],
    "Passed":[True,True,False,False]
}
df=pd.DataFrame(data)
print(df)

    age  Score  Passed
0  22.0   88.0    True
1  25.0   92.0    True
2  28.0    NaN   False
3   NaN   75.0   False


2. Essential ML Data Preprocessing Patterns

When preparing data for AI models, these are the top 4 operations you'll run constantly:

A. Handling Missing Data (Imputation)

Real-world datasets are messy. Neural networks will throw errors if they see NaN (Not a Number) values.

In [5]:
#Check Missing Values
print(df.isnull().sum())

#Fill missing numerical values with the mean/median
df["age"]=df["age"].fillna(df["age"].median())
df["Score"]=df["Score"].fillna(df["Score"].median())

print(df)

age       0
Score     1
Passed    0
dtype: int64
    age  Score  Passed
0  22.0   88.0    True
1  25.0   92.0    True
2  28.0   88.0   False
3  25.0   75.0   False


B. Filtering & Querying (Boolean Masking)

Just like NumPy boolean indexing, Pandas lets you filter rows using logical conditions.

In [7]:
# Filter rows where Score > 80
high_scorers = df[df["Score"] > 80]
print(high_scorers)

    age  Score  Passed
0  22.0   88.0    True
1  25.0   92.0    True
2  28.0   88.0   False


C. Feature Engineering & Mapping

Transforming text categories into numerical data so models can process them.

In [8]:
# Map boolean or categorical strings to 0/1
df["Passed"] = df["Passed"].astype(int)

D. Converting DataFrames back to NumPy Arrays

Once your data is cleaned, you convert it back to NumPy arrays (or PyTorch/TensorFlow tensors) for training.

In [12]:
# Extract features as a raw 2D NumPy array
X = df[["age", "Score" , "Passed"]].values
print(X)  # <class 'numpy.ndarray'>

[[22. 88.  1.]
 [25. 92.  1.]
 [28. 88.  0.]
 [25. 75.  0.]]


Pandas Series (1D)

A series is essentially a 1D Numpy array with an Index (row label)
Unlike NumPy arrays where you access elements only by position (scores[0]), in a Series you can access them by label (scores['Alice']) OR by position (scores.iloc[0]).

In [1]:
import pandas as pd
import numpy as np

# Creating a Series from a list
scores = pd.Series([85, 90, 78, 92], index=['Alice', 'Bob', 'Charlie', 'David'])
print(scores)

Alice      85
Bob        90
Charlie    78
David      92
dtype: int64


Pandas Dataframes (2D)

A DataFrame is a 2-dimensional table—think of an Excel sheet or a SQL table. Each column in a DataFrame is actually a Pandas Series.

In [2]:
# Creating a DataFrame from a dictionary of lists
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 92],
    "Passed": [True, True, False, True]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Score  Passed
0    Alice   24     85    True
1      Bob   27     90    True
2  Charlie   22     78   False
3    David   32     92    True


In [4]:
ai_df = pd.DataFrame({
    "Model_name" : ["Gemini","ChatGPT","Claude","Anthropic"],
    "Parameters_Billions":[70,100,200,300],
    "Accuracy":[90,80,75,95],
    "Is_opensource":[True,True,False,True]
})
print(ai_df)
print(ai_df.info())
acc_series=ai_df["Accuracy"]
print(type(acc_series))

  Model_name  Parameters_Billions  Accuracy  Is_opensource
0     Gemini                   70        90           True
1    ChatGPT                  100        80           True
2     Claude                  200        75          False
3  Anthropic                  300        95           True
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Model_name           4 non-null      object
 1   Parameters_Billions  4 non-null      int64 
 2   Accuracy             4 non-null      int64 
 3   Is_opensource        4 non-null      bool  
dtypes: bool(1), int64(2), object(1)
memory usage: 232.0+ bytes
None
<class 'pandas.core.series.Series'>


Data Selection & Indexing (loc vs iloc)

1. iloc (integer-location based)

Selects data using numerical index positions (0, 1, 2...), exactly like NumPy arrays.

In [5]:
# Format: df.iloc[row_index, column_index]

# Get the first row (Gemini)
print(ai_df.iloc[0])

# Get the first 2 rows, and first 2 columns
print(ai_df.iloc[0:2, 0:2])

Model_name             Gemini
Parameters_Billions        70
Accuracy                   90
Is_opensource            True
Name: 0, dtype: object
  Model_name  Parameters_Billions
0     Gemini                   70
1    ChatGPT                  100


2. loc (Label-location based)

Selects data using row labels and column names.

In [6]:
# Format: df.loc[row_label, column_name]

# Get all rows, but only 'Model_name' and 'Accuracy' columns
print(ai_df.loc[:, ["Model_name", "Accuracy"]])

  Model_name  Accuracy
0     Gemini        90
1    ChatGPT        80
2     Claude        75
3  Anthropic        95


3.Filtering Data (Boolean Indexing)

This is where Pandas shines for AI dataset preparation. You can filter rows based on conditions.

In [8]:
# Filter models where Accuracy is >= 80
high_acc = ai_df[ai_df["Accuracy"] >= 80]
print(high_acc)
print()
# Combine conditions with & (AND) or | (OR)
# Filter models that are Open Source AND have > 80 Accuracy
top_open_source = ai_df[(ai_df["Is_opensource"] == True) & (ai_df["Accuracy"] > 80)]
print(top_open_source)

  Model_name  Parameters_Billions  Accuracy  Is_opensource
0     Gemini                   70        90           True
1    ChatGPT                  100        80           True
3  Anthropic                  300        95           True

  Model_name  Parameters_Billions  Accuracy  Is_opensource
0     Gemini                   70        90           True
3  Anthropic                  300        95           True


In [15]:
print(ai_df.loc[[1,2],["Model_name","Parameters_Billions"]])
print()
print(ai_df.loc[ai_df["Parameters_Billions"]>90])

  Model_name  Parameters_Billions
1    ChatGPT                  100
2     Claude                  200

  Model_name  Parameters_Billions  Accuracy  Is_opensource
1    ChatGPT                  100        80           True
2     Claude                  200        75          False
3  Anthropic                  300        95           True
